dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
env:
  global:
  - secure: h3+XeWQNlYr1xj6BhpTY961GeIAabkto2INx3AwENxgLoRpftAbsBUeB4OD6dLn+U6RE+Ff0r7oE7cdbYe67gHN2CBtP8T5xepZcBhaH8hluRQ44hviK0FfvknxOhEFbtz23akJnk2/IY5vxKYwKDPsCN4LZFytEQ0ddkWv2gR6eOSAbD4xcQ7zfqWEWmIlw3VBg93VjImrLiJKLiPWj3p0gMH4qAcpOHojtcPmRaBeOH4wLGUaZ+B9weqggohZEr9Gg2piMW4ovH5VlVCJF7aYJjyZ7rBtl6J3n0inCzSMk0NrZaoSJvK9Ml8EjcCn16JvVQG/bvjTmpNPaF3qlNLLLcO3IsMu4gS1FzIBrYNl/s+TzCR3inKEasAdkXJzpfqmytW1GhlZ9gX5RqXDTgMhir6m0Mkh9naWjNZMuYY21TMhr2eIVOxo+3MP9O1IH1owfAIjcbyF9sa78RYfAOwGwo34ICi5olCUbtfOIbNTf02b6r2CjRoyqFful6xEBI21Qs1wTM/HoYqt8vEge5qU+Aw9hmuN9GP2DK4oO3uzasokXMZaOCi3rcqtQa+Ryfpgw3c8kPmDYudi7jR0QxttR0PZesD0BOEqvFtyqytyxEOr6MgQu3zu/2WPagSXHMbrcwsauKTyTIl3DRAlATkZYHJq8GwoqPLaEij0gGdg=
  - secure: sbx4drAyE9YAla8TpVptTCTspshOctadnNMI1reOytWLICD2B0zR7VtH3Fxa9HQoUgEN6l9xA+5fV1nY7b2d4TDg5Ov90cVGMV/b8YU6F2xuepPOSD2ywX1+rt+iaUtx34YCj9bFbiHf4dx3HX0aGoGtAlqgILHTlaoCWe1m8lER1sj1vol939ChWC7IrmmCp3vDLTq+gmL3dlHAgSnIKUM03UrnUwj4XawNRsjN0b96CV7QLmezQ9u2yAZbFRnRzq15HLxFSbzH8HA5+E0C87ZVpwqFvKlPzG+s470CwfIx2Blf8+8TyDPXv9gcHf3Uljk6htblWh0UPyIx6EK/ySIAePuYDKKkz6D57OfYw8vVOnHZzJ8Sz7pRvNXtI2aMBrJvLjXNDT03xVH8DfBxSPADo6LcmwD+ydP7bhbeQm1TsTcww6My1C8/bAhq2dw82mB9oZyjMDgkm6omoPaFxM2V/OjF2JzYnoeGtBL0zilfcOM2UsGV/05UBIoHQ2F84fQ9rm8mV2BtgUvvDhed5xomkoPoiZJR2gzV6CO5yfpbroTA+YK0mKfIkZT5t9OU5fjjZC16ACp+V551UEFgEIkl8z6dPeyfZxKkSprki6FfVkZu9I/1VEJnVTpOw+/zH8SUo2jhJDJ6VHgrDsE4m4eIU/s6eiwYpq0dCax21rY=
  - secure: VgqE4dpjJK5mOwA20ZEFXktyuXyNAyUuzhEkGgsnUK37p/i6+y0MvCdi1BSHRS6+AXZQB37JaAnxscrNv3be3pAwtGOwNSAvwSHBuOPj8IikIxWtXhfTU9kUuD9rhgD0FPwZhO+bWAl2vSBId/ZSCIK/JhwU2FFkQAiiahLFj4TgaBNmm0AsxxsF+L8Agp4RcofyU8hoYxDj9nCRYLUImJK1Is2SG8X2XYFb5F69KgAhj0HWsPK5DzHgV/rHUigfjzgHVKqovMnwOCMzv3eL7mX+cPWr1FxgUd4o7c9Njst4yF3AEllEEWD/uDHXnlWeb4i5bsQHh3i59EFtQP2J0SGCVNxQGdSf6U13GF45yuj8xSL3QRPVSKiznYfMeWCcmxcrMYVcCr/5vCbL9JHcHMrsejwC/B1MQoulU9V7nndC/l8wLBf56+bmKfERRt8/Zx4gxn9dkvs9qSBKnMWVBdqkB6HJo6P1NyFy0QNq4/XOQ+3nGQts4nAmhO3LniFX+59N8FuDz4FqEkhB/sD6w7FyUkLcditiklUAq93PgmdacJzm8griPzjbLZ32ha5LZSwgCfN/3oL+hhh/sjjS6K0555E+nNuT3S580nsKSIF2TGcxT6A8ZSzDuYWXy6FugsWRensdkZTT7npDfQa+vkSn/OA1KlVCBeO6qNI6yrc=
install: true
script: bash travis-build.bash
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: NcVLU1HMupWu6ylan2NR7EMQ4zSETjKy12rRZAhoczoxOZdiwk0j8Tpn0sBum+aFocm5RKyP1E1jIuPAxDIoF6u5S5Tja+g9+T5aC+mTd5b6WkuKwoGwiDKADpKH43AHfZMTlilZhhBep9OsLo5rFblkGdvHAUGfwwjCx801JyNfn+3imBdwBE1myrxq6VvVlUavQwVkPkx80XrK/pmBVwWheGwKlfWM/xRdDc2nWqQ0F2ff8BgSJ4TZsH9GqIsxEqCDlDuL/KNqfaaS9o3UUaxgFABCyTmp5LErMwRQjMWJlsreorE4Pa9f+VNR/KAGDv67nkRAQ8IIcAag8Ax+gsqS6Omw+95oALAkSdvazX5qFNSqQKeULwpKzn+TJAY6hkSdSzz8/rFtZxiMIHZ5eKZUKU3Qa/NnHzPTnyOsj78pwbi+tzpwMEt/XouIrqxOGBQobYGhPVpSIwVBZadP2/xuUo3CUUkFrZfA9qZZcPC6Eoe1nLmwMdJLypOQbO30BaVAUOqAvHZKNImElKRIUbztd0cLJJLHLKzGh6MC5sNrzDA6D/BbSOH5j6lY6ub+mK5QuF2/7ORpBKKggjRIgpSvCM2PV6GuLQePD7QZJhSoPjpXk01fzzy+hMsc+Z6PyrTCPa/W8ijVcRaS83N9nBtOWN6rz0tDUtxXP8CDuso=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
